name = "ChessEngine"
uuid = "2eacc985-a635-41e1-b67f-45fa7ceb5b4d"
authors = ["Bjarke Hautop <bjarke.hautop@gmail.com> and contributors"]
version = "0.0.1-DEV"

[compat]
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
